# Generated by Django 4.1.3 on 2023-02-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0002_hey_there_delete_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=10000)),
                ('captured_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='hey_there',
        ),
    ]
